---
pipeline:
  build:
    app:
      image: golang
      environment:
        - GOPATH=/drone
      commands:
        - go get -v .
        - go build -v .
    container:
      image: docker
      commands:
        - docker build .
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

