---
pipeline:
  build:
    image: alpine
    environment:
      - GOPATH=/drone
    commands:
      - apk add go git docker
      - go get -v .
      - go build -v .
      - docker build .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

